### ISSUE TITLE
Bug when run python detect.py && detect_track.py && detect_track_stgcn.py

### ISSUE THREAD

**Issue by C0NGTRI123** [Bigtuo/YOLOv7-Pose-Bytetrack-STGCN#1]
### When i run terminal 
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.1, device='', exist_ok=False, hide_conf=False,                                                                                                                                                                                       
hide_labels=False, img_size=960, iou_thres=0.45, kpt_label=True, line_thickness=3, match_thresh=0.8, name='exp', nosave=False, project='runs/detect', save_bin=False, save_conf=False, save_crop=False, save_txt=False, save_txt_tidl=False, source='pose_test1.mp4', track_buffer=30, track_thresh=0.5, update=False, view_img=True, weights='yolov7-w6-pose.pt')
Traceback (most recent call last):
  File "/home/dinhtra/anaconda3/envs/cms_ai/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/dinhtra/anaconda3/envs/cms_ai/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pkg_resources._vendor.pyparsing.exceptions.ParseException: Expected string_end, found '+'  (at char 3), (line:1, col:4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect_track.py", line 241, in <module>
    check_requirements(exclude=('tensorboard', 'pycocotools', 'thop'))
  File "/home/dinhtra/Desktop/YOLOv7-Pose-Bytetrack-STGCN/utils/general.py", line 110, in check_requirements
    requirements = [f'{x.name}{x.specifier}' for x in pkg.parse_requirements(file.open()) if x.name not in exclude]
  File "/home/dinhtra/Desktop/YOLOv7-Pose-Bytetrack-STGCN/utils/general.py", line 110, in <listcomp>
    requirements = [f'{x.name}{x.specifier}' for x in pkg.parse_requirements(file.open()) if x.name not in exclude]
  File "/home/dinhtra/anaconda3/envs/cms_ai/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3102, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/dinhtra/anaconda3/envs/cms_ai/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 105, in __init__
    f'Parse error at "{ requirement_string[e.loc : e.loc + 8]!r}": {e.msg}'
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+https:/'": Expected string_end

**Comment by Bigtuo** [comment]
> ### When i run terminal
> Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.1, device='', exist_ok=False, hide_conf=False, hide_labels=False, img_size=960, iou_thres=0.45, kpt_label=True, line_thickness=3, match_thresh=0.8, name='exp', nosave=False, project='runs/detect', save_bin=False, save_conf=False, save_crop=False, save_txt=False, save_txt_tidl=False, source='pose_test1.mp4', track_buffer=30, track_thresh=0.5, update=False, view_img=True, weights='yolov7-w6-pose.pt') Traceback (most recent call last): File "/home/dinhtra/anaconda3/envs/cms_ai/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in **init** req = REQUIREMENT.parseString(requirement_string) File "/home/dinhtra/anaconda3/envs/cms_ai/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 1141, in parse_string raise exc.with_traceback(None) pkg_resources._vendor.pyparsing.exceptions.ParseException: Expected string_end, found '+' (at char 3), (line:1, col:4)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "detect_track.py", line 241, in check_requirements(exclude=('tensorboard', 'pycocotools', 'thop')) File "/home/dinhtra/Desktop/YOLOv7-Pose-Bytetrack-STGCN/utils/general.py", line 110, in check_requirements requirements = [f'{x.name}{x.specifier}' for x in pkg.parse_requirements(file.open()) if x.name not in exclude] File "/home/dinhtra/Desktop/YOLOv7-Pose-Bytetrack-STGCN/utils/general.py", line 110, in requirements = [f'{x.name}{x.specifier}' for x in pkg.parse_requirements(file.open()) if x.name not in exclude] File "/home/dinhtra/anaconda3/envs/cms_ai/lib/python3.7/site-packages/pkg_resources/**init**.py", line 3102, in **init** super(Requirement, self).**init**(requirement_string) File "/home/dinhtra/anaconda3/envs/cms_ai/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 105, in **init** f'Parse error at "{ requirement_string[e.loc : e.loc + 8]!r}": {e.msg}' pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+https:/'": Expected string_end

See if 'tensorboard', 'pycocotools', 'thop' are missing; Or you can comment out the "check_requirements" line.
